name: "CD"

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: CD

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy unet.tech
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
