name: "CD"

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CD:
    runs-on: ubuntu-latest
    env:
      UNET_DOMAIN: unet.tech

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to unet.tech
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
