name: "CI"

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      UNET_DEPLOY: staging

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose --bins --examples --tests
    - name: Deploy ${{github.head_ref}}.unet-staging.com
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
