name: "main"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Build and Deploy to ${{github.head_ref || 'main'}}
      run: cargo build --verbose
      env:
        STACK_NAME: ${{github.head_ref || 'main'}}
    - name: Test
      run: cargo test --verbose
