name: "On Push"

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    # Use the 'prod' environment when pushing to the main branch, otherwise use
    # 'staging'.
    environemnt: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}

    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Check
      run: cargo check --verbose --bins --examples --tests
    -
      name: Deploy to ${{ github.ref == 'refs/heads/main' && 'unet.tech' || "${{github.ref_name }}.unet-staging.com" }}
      run: cargo run deploy
    -
      name: Test
      run: cargo test --verbose
