name: "On Push"

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Check
      run: cargo check --verbose --bins --examples --tests
    -
      name: Staging Deploy
      run: cargo run deploy
      environment: staging
    -
      name: Staging Test
      run: cargo test --verbose
      environment: staging
    -
      name: Prod Deploy
      run: cargo run deploy
      if: github.ref == 'refs/heads/main'
      environment: prod
    -
      name: Prod Test
      run: cargo test --verbose
      if: github.ref == 'refs/heads/main'
      environment: prod
