name: "On Push"

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest
    environment: staging
    # We don't want the staging stack being deployed from multiple workflows at
    # the same time
    concurrency:
      group: "test:${{ github.ref }}"

    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Check
      run: cargo check --verbose --bins --examples --tests
    -
      name: Deploy to "${{ github.ref_name }}.unet-staging.com"
      run: cargo run deploy
    -
      name: Test againt staging deployment
      run: cargo test --verbose

  Deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: Test
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: deploy

    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Deploy to unet.tech
      run: cargo run deploy
    -
      name: Test against production deployment
      run: cargo test --verbose
