name: "push"

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
    - name: Check
      run: cargo check --verbose --bins --examples --tests
    - name: Deploy ${{github.head_ref}}.unet-staging.com
      run: cargo build --verbose
      environment: staging
    - name: Staging Test
      run: cargo test --verbose
      environment: staging
    - name: Deploy unet.tech
      run: cargo build --verbose
      if: github.ref == 'refs/heads/main'
      environment: prod

    - name: Prod Test
      run: cargo test --verbose
